version: "3.3"

services:

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8350:8978"
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
